"""Single source of truth for OWASP Top 10:2025 coverage and learning analysis."""

from __future__ import annotations


def _analysis(
    *,
    actor: str,
    asset: str,
    precondition: str,
    weakness: str,
    mechanism: str,
    failed_decision: str,
    attack_technique: str,
    trust_boundary: str,
    security_property: str,
    likelihood: str,
    threat_chain: str,
    impact: str,
    if_unfixed: str,
    vulnerable_heading: str,
    secure_heading: str,
    control: str,
    why_it_works: str,
    comparison: str,
    observed_change: str,
    legitimate_check: str,
    before: str,
    after: str,
    mistake: str,
    correction: str,
    redo: str,
    course_topic: str,
    course_source: str,
    supports: str,
    does_not_prove: str,
    residual_risks: list[str],
) -> dict:
    return {
        "what": {
            "actor": actor,
            "asset": asset,
            "precondition": precondition,
            "weakness": weakness,
            "mechanism": mechanism,
            "failed_decision": failed_decision,
            "attack_technique": attack_technique,
            "trust_boundary": trust_boundary,
        },
        "why": {
            "security_property": security_property,
            "likelihood": likelihood,
            "threat_chain": threat_chain,
            "impact": impact,
            "if_unfixed": if_unfixed,
        },
        "how": {
            "vulnerable_heading": vulnerable_heading,
            "secure_heading": secure_heading,
            "control": control,
            "why_it_works": why_it_works,
            "comparison": comparison,
            "observed_change": observed_change,
            "legitimate_check": legitimate_check,
        },
        "learning": {
            "before": before,
            "after": after,
            "mistake": mistake,
            "correction": correction,
            "redo": redo,
            "course_topic": course_topic,
            "course_source": course_source,
        },
        "boundary": {
            "supports": supports,
            "does_not_prove": does_not_prove,
            "residual_risks": residual_risks,
        },
    }


def _contract(
    v_positive: tuple[str, str],
    v_security: tuple[str, str],
    s_security: tuple[str, str],
    s_positive: tuple[str, str],
) -> list[dict[str, str]]:
    cases = (
        ("v_positive", "Vulnerable normal use", v_positive),
        ("v_security", "Vulnerable unsafe behaviour", v_security),
        ("s_security", "Same attack, more secure path", s_security),
        ("s_positive", "More secure normal use", s_positive),
    )
    return [
        {"id": case_id, "label": label, "expected": values[0], "oracle": values[1]}
        for case_id, label, values in cases
    ]


LABS = [
    {
        "id": "a01",
        "owasp": "A01:2025",
        "name": "Broken Access Control",
        "depth": "Deep",
        "scenario": "Alice changes one object ID and receives Bob's order.",
        "control": "Bind the requested order to the authenticated owner.",
        "analysis": _analysis(
            actor="Alice, an authenticated customer",
            asset="Bob's order and synthetic address",
            precondition="Alice has a normal account and can change order 101 to 202.",
            weakness="Missing object-level authorization (IDOR)",
            mechanism="The vulnerable query selects an order by client-supplied ID only.",
            failed_decision="Successful login is treated as permission to read any order ID.",
            attack_technique="Change one identifier in an otherwise valid authenticated request.",
            trust_boundary="A browser-controlled order ID crosses into the server's authorization and database lookup; Alice's authenticated identity is separate server-side context.",
            security_property="Confidentiality, privacy and separation between customer accounts",
            likelihood="Low effort: the attacker needs only a customer account and an observed or guessable ID.",
            threat_chain="Ordinary customer login -> change order 101 to 202 -> owner-blind lookup -> Bob's row crosses into Alice's response.",
            impact="The demonstrated result exposes another customer's order. Repetition could turn one missing check into cross-account disclosure.",
            if_unfixed="Systematic ID enumeration could expose many customer records, causing privacy harm, fraud opportunities, incident cost and loss of trust.",
            vulnerable_heading="The object ID becomes permission",
            secure_heading="Ownership is checked with the object",
            control="Query by both order ID and the authenticated server-side owner ID, then deny by default.",
            why_it_works="Alice cannot make Bob's row satisfy Alice's server-side owner ID, even though she controls the order number.",
            comparison="Vulnerable trusts login plus the requested ID; secure evaluates the principal, read action and object ownership together.",
            observed_change="Alice requesting order 202 changes from 200 with Bob's fields to a data-free 404.",
            legitimate_check="Alice can still retrieve her own order 101 with status 200.",
            before="I treated successful login as the main access-control check.",
            after="I now check the principal, action and object together at the point where protected data is used.",
            mistake="The reasoning error was collapsing authentication into authorization: knowing that the caller is Alice does not decide whether Alice may read order 202.",
            correction="The paired experiment corrects that decision by adding Alice's owner ID to the lookup; Bob's row disappears while Alice's order still works.",
            redo="If I extended this module, I would centralise the same object policy and test read, write and bulk routes instead of treating one protected read as complete coverage.",
            course_topic="Zero Trust, least privilege and authorizing every request",
            course_source="Week 4 Engineering, slides 53-55; Week 2 Engineering, slides 34-35",
            supports="The experiment supports a claim about unauthorised reading through one ID-only order route.",
            does_not_prove="It does not prove that write routes, bulk endpoints, roles or shared objects are correctly authorized.",
            residual_risks=["write operations", "other object routes", "role and sharing rules"],
        ),
        "deep_dive": {
            "attack_chain": [
                "Alice authenticates with an ordinary customer account.",
                "She changes only the order identifier from 101 to 202.",
                "The database query selects Bob's row because it constrains the ID but not the owner.",
                "Bob's order fields cross the response boundary even though Alice is not authorized for that object.",
            ],
            "insufficient_fix": "Hiding sequential IDs or checking only that Alice is logged in would make guessing harder, but neither expresses the missing object-ownership policy.",
            "control_choice": "I put the owner constraint in the same database lookup as the object ID. This prevents another customer's row from being selected at all, instead of fetching it first and relying on a later check.",
            "evidence_reading": "The decisive evidence is not just a different status: the vulnerable response is 200 with owner=bob, the secure response is 404 with no Bob marker, and Alice's own order still returns 200.",
            "tradeoff": "A data-free 404 avoids confirming that order 202 exists, but every read and write path still needs the same authorization rule; one protected route is not a complete access-control design.",
        },
        "contract": _contract(
            ("Alice reads order 101.", "status 200 and owner=alice"),
            ("Alice reads Bob's order 202.", "status 200, owner=bob and authorized=false"),
            ("The same order 202 request is denied without Bob's data.", "status 404 and sensitive_data_returned=false"),
            ("Alice still reads order 101.", "status 200 and owner=alice"),
        ),
    },
    {
        "id": "a02",
        "owasp": "A02:2025",
        "name": "Security Misconfiguration",
        "depth": "Deep",
        "scenario": "A controlled error sends synthetic internal diagnostics to the client.",
        "control": "Separate generic client errors from minimised server diagnostics.",
        "analysis": _analysis(
            actor="Unauthenticated local lab visitor",
            asset="Internal paths, query shape and configuration metadata",
            precondition="The visitor can supply an input that reaches a server error path.",
            weakness="Information exposure through an unsafe error renderer",
            mechanism="The vulnerable handler serializes fixed internal-style details into the 500 response.",
            failed_decision="Diagnostics intended for operators are allowed to cross the client trust boundary.",
            attack_technique="Trigger exceptional paths and collect the returned implementation details.",
            trust_boundary="An exception moves from server-only execution and diagnostics into a client-facing response; operator data must stop at that boundary.",
            security_property="Confidentiality of implementation, configuration and diagnostic data",
            likelihood="The demonstrated error path is unauthenticated and can be triggered repeatedly.",
            threat_chain="Trigger a reachable failure -> unsafe renderer serializes internal markers -> client collects them -> follow-up probing becomes more targeted.",
            impact="The details reduce attacker uncertainty and can guide more focused follow-up tests; real errors may also contain secrets or personal data.",
            if_unfixed="Every reachable exception can become a reconnaissance channel, even when framework debug mode is disabled.",
            vulnerable_heading="Operator diagnostics reach the client",
            secure_heading="Client and operator information are separated",
            control="Return a generic code and request ID, while storing one correlated, minimised event on the server.",
            why_it_works="The client retains a useful reference without receiving trace, path, SQL or configuration details.",
            comparison="Vulnerable gives one audience both the error and operator diagnostics; secure gives the client a generic reference and keeps a minimised correlated event server-side.",
            observed_change="The 500 response loses every internal marker and gains a request ID linked to one local event.",
            legitimate_check="A normal order lookup still returns 200 and the interactive debugger remains disabled.",
            before="I saw error messages mainly as a debugging and usability concern.",
            after="I now treat failure handling as a security boundary and separate least disclosure from operator diagnosability.",
            mistake="The incomplete fix was focusing only on framework debug mode; a custom error renderer can still disclose internals while debug and the interactive debugger are both off.",
            correction="The experiment separates the audiences and verifies both sides: no internal markers reach the client, but one request ID still correlates to a minimised event.",
            redo="If I extended this module, I would inventory every error handler and test log access, retention and secret filtering rather than generalising from one controlled path.",
            course_topic="Reducing attacker uncertainty, evidence traces and data minimisation",
            course_source="Week 3 Core, slides 23-25; Week 4 Engineering, slides 47-48; Week 5 Privacy, slides 11-14",
            supports="The experiment supports a claim about one controlled diagnostic-disclosure policy.",
            does_not_prove="It does not claim remote code execution or assess every error handler, proxy, log store or retention rule.",
            residual_risks=["other error handlers", "log access and retention", "secrets accidentally written server-side"],
        ),
        "deep_dive": {
            "attack_chain": [
                "An unauthenticated caller supplies the controlled value that reaches an exception path.",
                "The vulnerable renderer gathers trace, path, query-shape and configuration-style details.",
                "Those operator-oriented details are serialized into the client-facing 500 response.",
                "The caller can repeat the request and use the extra detail to reduce uncertainty about the application.",
            ],
            "insufficient_fix": "Turning framework debug mode off is necessary but does not fix a custom handler that still serializes internal details. Removing only the stack trace would also leave the path, query shape and configuration marker exposed.",
            "control_choice": "I separated audiences: the client receives a stable error code and request ID, while one minimised server event retains the correlation needed for diagnosis.",
            "evidence_reading": "The vulnerable response contains all four synthetic diagnostic fields. The secure response contains none of them, yet its request ID matches exactly one minimised event and a normal lookup remains 200.",
            "tradeoff": "Server-side logging moves rather than eliminates sensitive-data risk. Access control, retention, tamper resistance and secret filtering are still required for the event store.",
        },
        "contract": _contract(
            ("Order 101 lookup works.", "status 200 and order id=101"),
            ("The controlled error returns synthetic internal markers.", "status 500 and trace/path/config markers present"),
            ("The same error returns only a generic response and request ID.", "status 500, internal markers absent and one correlated event"),
            ("Valid lookup and safe runtime configuration remain available.", "status 200, debug=false and interactive_debugger=false"),
        ),
    },
    {
        "id": "a03",
        "owasp": "A03:2025",
        "name": "Software Supply Chain Failures",
        "depth": "Compact",
        "scenario": "A floating latest selector accepts an unreviewed local artefact.",
        "control": "Use a trusted version pin and a digest from a separate reviewed lab manifest.",
        "analysis": _analysis(
            actor="A build process consuming a synthetic package repository",
            asset="Build and dependency integrity",
            precondition="A newer or changed artefact appears under a trusted-looking package name.",
            weakness="Floating dependency selection without trusted byte-level verification",
            mechanism="The vulnerable resolver chooses the highest version and accepts its bytes without a digest.",
            failed_decision="Package name and recency are treated as evidence of review and integrity.",
            attack_technique="Influence the artefact source while preserving a plausible name or version.",
            trust_boundary="Repository-controlled package identity and bytes cross into the trusted build; the expected version and digest must come from a separately reviewed source.",
            security_property="Integrity of dependencies and the software build",
            likelihood="The path becomes plausible wherever an attacker or compromised source can publish or replace artefacts.",
            threat_chain="Publish or replace plausible package bytes -> floating resolver selects them -> build accepts them without independent verification -> dependency code inherits build privileges.",
            impact="Real dependency code may execute with developer, CI or application privileges and reach downstream users.",
            if_unfixed="A build silently extends trust from one reviewed release to unknown future or modified bytes.",
            vulnerable_heading="Latest is treated as trusted",
            secure_heading="Reviewed identity and bytes are fixed",
            control="Pin version 2.4.1 and verify its SHA-256 against a separate reviewed lab manifest.",
            why_it_works="The resolver no longer follows an unreviewed version, and changed pinned bytes cannot match the fixed manifest digest.",
            comparison="Vulnerable extends trust to whichever release looks newest; secure fixes both the reviewed release identity and its expected bytes outside the repository response.",
            observed_change="Version 2.4.2 is ignored and modified 2.4.1 bytes return 422.",
            legitimate_check="The reviewed 2.4.1 artefact remains usable.",
            before="I thought a package version or a hash was automatically a trust signal.",
            after="I now separate identity from integrity: a pin selects the release, while a digest works only when its expected value is kept outside the artefact being checked.",
            mistake="The reasoning error was treating a hash as self-authenticating; a digest supplied by the same compromised source as the artefact would only confirm the attacker's bytes.",
            correction="The local manifest supplies the reviewed pin and expected digest independently, so both an unreviewed newer release and changed pinned bytes have observable outcomes.",
            redo="If I extended this module, I would add transitive-dependency inventory and signature/provenance verification, while keeping those claims separate from this checksum experiment.",
            course_topic="Supply-chain trust and trusted hash values",
            course_source="Week 1 Engineering, slides 21-22; Week 7 Engineering, slide 5",
            supports="The experiment supports a local claim about floating selection and pinned-artefact integrity.",
            does_not_prove="It does not assess registries, maintainers, signatures, transitive dependencies or malicious reviewed code.",
            residual_risks=["manifest compromise", "transitive dependencies", "maintainer and build-system compromise"],
        ),
        "contract": _contract(
            ("The reviewed artefact is accepted.", "selected_version=2.4.1 and accepted=true"),
            ("A newer unreviewed artefact is selected.", "selected_version=2.4.2 and contains_untrusted_marker=true"),
            ("The reviewed pin remains selected and changed pinned bytes are rejected.", "version stays 2.4.1; tampered bytes return 422"),
            ("The trusted pinned artefact is accepted.", "digest matches and accepted=true"),
        ),
    },
    {
        "id": "a04",
        "owasp": "A04:2025",
        "name": "Cryptographic Failures",
        "depth": "Compact",
        "scenario": "Equal passwords produce equal fast, unsalted stored values.",
        "control": "Use unique salts and a memory-hard password KDF.",
        "analysis": _analysis(
            actor="An attacker with an offline copy of synthetic credential records",
            asset="Password confidentiality and separation between accounts",
            precondition="The attacker has obtained stored password records and can guess offline.",
            weakness="Fast, deterministic and unsalted password hashing",
            mechanism="Plain SHA-256 gives equal passwords equal values and makes every guess cheap.",
            failed_decision="A general-purpose hash is treated as sufficient password storage.",
            attack_technique="Compare records for reuse and run high-rate offline candidate guessing.",
            trust_boundary="A password crosses into a long-lived verifier record; after a database leak, the attacker controls an offline guessing loop outside online rate limits.",
            security_property="Confidentiality of password-derived credential material",
            likelihood="Offline access removes online rate limits; guessing speed is controlled by the stored algorithm and attacker hardware.",
            threat_chain="Copy verifier records -> spot equal unsalted hashes -> reuse precomputation and cheap guesses -> recover weak candidates or identify reused passwords.",
            impact="Password reuse becomes visible and weak candidates can be tested across many accounts.",
            if_unfixed="One database leak can rapidly amplify weak or reused passwords into account compromise attempts.",
            vulnerable_heading="Hashing is fast and deterministic",
            secure_heading="Each record has salt and work factor",
            control="Generate a unique 16-byte salt and derive each record with scrypt N=2^14, r=8, p=5.",
            why_it_works="Salts remove cross-record equality and precomputation reuse; scrypt makes every offline guess more expensive.",
            comparison="Vulnerable uses one fast deterministic transform for every account; secure gives each record a unique salt and a deliberately costly memory-hard derivation.",
            observed_change="Equal passwords no longer create equal records, while the correct candidate still verifies.",
            legitimate_check="Correct verification succeeds and a wrong candidate fails without exposing stored values.",
            before="I treated the word hashed as evidence that a password was safely stored.",
            after="I now ask whether the design has a unique salt and a deliberately costly password KDF, because they address different parts of the offline attack.",
            mistake="The reasoning error was asking only whether the password was hashed, not whether equal records leak reuse or how cheaply an offline attacker can test each guess.",
            correction="The paired comparison makes both corrections visible: unique salts remove equality and scrypt adds per-guess work while legitimate verification still succeeds.",
            redo="If I extended this module, I would benchmark parameters on deployment hardware and design upgrade and pepper-key handling rather than freezing one lab setting forever.",
            course_topic="Password hashing, salts and attacker work factor",
            course_source="Week 7 Engineering, slides 17-18; Week 5 Engineering, slides 52-58",
            supports="The experiment supports a comparison of equality leakage and verification under two local storage designs.",
            does_not_prove="It does not cover password strength, breached-password checks, pepper storage, rate limiting or future parameter upgrades.",
            residual_risks=["weak user passwords", "pepper and key management", "parameter migration"],
        ),
        "contract": _contract(
            ("The correct candidate verifies under SHA-256.", "candidate_verified=true"),
            ("Equal passwords produce equal stored values.", "hashes_equal=true and salt lengths are zero"),
            ("Unique salts separate equal passwords.", "hashes_equal=false and salt lengths are 16"),
            ("The correct candidate still verifies under scrypt.", "candidate_verified=true and sensitive values are absent"),
        ),
    },
    {
        "id": "a05",
        "owasp": "A05:2025",
        "name": "Injection",
        "depth": "Deep",
        "scenario": "SQL-shaped input changes a query and exposes a hidden product.",
        "control": "Keep query structure fixed and bind the input as data.",
        "analysis": _analysis(
            actor="Unauthenticated local lab visitor",
            asset="Confidentiality of hidden product 99",
            precondition="The visitor controls the q search parameter.",
            weakness="SQL injection through string-built query text",
            mechanism="The vulnerable route inserts q into an SQL f-string before SQLite parses it.",
            failed_decision="Untrusted data is allowed to become database control syntax.",
            attack_technique="Close the intended string, add a true condition and comment out the remaining restriction.",
            trust_boundary="The public q parameter crosses from an HTTP request into the database parser; user data must not enter the SQL grammar at that boundary.",
            security_property="Confidentiality at the application-to-database boundary",
            likelihood="The route is unauthenticated, the input is directly controllable and the request can be automated.",
            threat_chain="Supply SQL-shaped q text -> string interpolation changes statement grammar -> public-row restriction is bypassed -> hidden product crosses into the response.",
            impact="The demonstrated query reveals a hidden row; broader privileges or other query types could increase confidentiality, integrity or availability consequences.",
            if_unfixed="Every interpolated query remains an unintended instruction channel whose impact depends on the database account and statement.",
            vulnerable_heading="Input becomes SQL structure",
            secure_heading="Input remains a bound value",
            control="Use a parameter placeholder and pass the complete search value separately.",
            why_it_works="Quotes, operators and comments remain inside a data value instead of changing the statement grammar.",
            comparison="Vulnerable builds instructions after receiving q; secure fixes the instruction structure first and binds the entire q value into one data slot.",
            observed_change="The same payload still returns 200 but the hidden marker changes from present to absent.",
            legitimate_check="A normal search for Security returns the same public product and database state remains unchanged.",
            before="I associated SQL injection mainly with suspicious characters and known payloads.",
            after="I now treat injection as a data/control separation problem and use parameterisation rather than trying to predict every malicious string.",
            mistake="The reasoning error was focusing on blocking familiar payload characters; blacklists try to predict syntax instead of preventing input from becoming syntax.",
            correction="Parameter binding changes the trust decision itself: the identical payload is parsed as one value, the hidden row disappears, and an ordinary search still works.",
            redo="If I extended this module, I would inventory every raw query and separately constrain dynamic identifiers and database privilege instead of claiming one parameterised value solves all injection.",
            course_topic="Separating untrusted data from control instructions",
            course_source="Week 2 Engineering, slides 36-40",
            supports="The experiment supports a read-only confidentiality claim for one interpolated product search.",
            does_not_prove="It does not demonstrate modification, deletion, authentication bypass, every ORM fragment or least-privilege database configuration.",
            residual_risks=["dynamic identifiers", "other interpreters and raw ORM fragments", "excessive database privileges"],
        ),
        "deep_dive": {
            "attack_chain": [
                "The caller supplies SQL-shaped text through the public q parameter.",
                "String interpolation inserts that text into the statement grammar rather than a value slot.",
                "The injected condition changes which rows satisfy the query and bypasses the public-product filter.",
                "The hidden synthetic product is returned even though the HTTP status remains 200 in both variants.",
            ],
            "insufficient_fix": "A blacklist for quotes, comments or OR would depend on one database grammar and one encoding path. Escaping is also context-specific and easy to apply inconsistently.",
            "control_choice": "I used a parameter placeholder so the query structure is fixed before q is supplied. The database receives q as one value and cannot reinterpret its characters as new operators.",
            "evidence_reading": "Status code alone cannot distinguish the outcomes. The vulnerable response includes product 99 and hidden_exposed=true; the secure response is still 200 but has an empty product list, while a normal Security search still matches.",
            "tradeoff": "Parameters protect values, not dynamic table or column names. Other queries, raw ORM fragments, database privileges and downstream output handling remain separate review points.",
        },
        "contract": _contract(
            ("A normal public search works.", "status 200 and public product returned"),
            ("The payload exposes the hidden product.", "hidden_exposed=true and hidden marker present"),
            ("The identical payload is treated as text.", "status 200, empty products and hidden_exposed=false"),
            ("Normal search behaviour remains available.", "same public result and unchanged database rows"),
        ),
    },
    {
        "id": "a06",
        "owasp": "A06:2025",
        "name": "Insecure Design",
        "depth": "Compact",
        "scenario": "The same valid welcome coupon can be replayed by one customer.",
        "control": "Enforce the one-use invariant in authoritative state.",
        "analysis": _analysis(
            actor="Alice, an ordinary authenticated customer",
            asset="Order pricing integrity and promotion budget",
            precondition="Alice has one valid WELCOME10 request that can be submitted again.",
            weakness="The one-use business rule is absent from the design",
            mechanism="The vulnerable route validates the coupon text but never models prior redemption.",
            failed_decision="A request that is individually valid is assumed to be valid in every state.",
            attack_technique="Replay the same well-formed business action, including concurrently.",
            trust_boundary="A repeated client request crosses into authoritative promotion state; only the database can decide whether this user-coupon transition has already occurred.",
            security_property="Integrity of pricing and business state",
            likelihood="No malformed input or elevated privilege is needed; simple automation can repeat the request.",
            threat_chain="Obtain one valid coupon action -> replay it -> stateless validation accepts it again -> duplicate redemptions corrupt pricing and promotion state.",
            impact="Repeated discounts corrupt promotion rules and can scale into direct financial loss and accounting inconsistency.",
            if_unfixed="Scripts or concurrent requests can repeatedly consume a benefit intended for one use.",
            vulnerable_heading="A valid request has no state rule",
            secure_heading="One use becomes a database invariant",
            control="Check redemption inside an authoritative transaction and enforce uniqueness in the database.",
            why_it_works="The second state transition cannot be committed for the same user and coupon, including under a race.",
            comparison="Vulnerable validates each request in isolation; secure evaluates the requested transition against stored history and a database uniqueness invariant.",
            observed_change="Alice's second use changes from 201 accepted to 409 rejected.",
            legitimate_check="Alice's first use and Bob's independent first use still return 201.",
            before="I looked for insecure input more often than missing business rules.",
            after="I now write important rules as state invariants and enforce them where concurrency and replay are authoritative.",
            mistake="The reasoning error was assuming that valid syntax plus a valid coupon makes the action safe; the missing question was whether this state transition is still allowed.",
            correction="The secure design represents prior use and rejects a duplicate at the authoritative transaction boundary while preserving first use for Alice and Bob.",
            redo="If I extended this module, I would add concurrent-worker tests and specify refund, expiry and reservation semantics before expanding the promotion model.",
            course_topic="Security invariants, secure design and safe state transitions",
            course_source="Week 4 Engineering, slide 52; Week 2 Engineering, slides 34-35",
            supports="The experiment supports a one-use coupon replay claim for the local transaction and schema.",
            does_not_prove="It does not cover all promotion combinations, distributed transactions, refunds or reservation workflows.",
            residual_risks=["other promotion rules", "distributed state", "refund and rollback behaviour"],
        ),
        "contract": _contract(
            ("Alice's first coupon use is accepted.", "status 201 and redemption_number=1"),
            ("Alice's second use is also accepted.", "second status 201 and redemption_number=2"),
            ("Alice's second secure use is rejected.", "second status 409 and accepted=false"),
            ("Another eligible customer can use it once.", "Bob status 201 and accepted=true"),
        ),
    },
    {
        "id": "a07",
        "owasp": "A07:2025",
        "name": "Authentication Failures",
        "depth": "Deep",
        "scenario": "A copied Admin token still works after the user logs out.",
        "control": "Revoke authoritative server-side session state.",
        "analysis": _analysis(
            actor="Eve, already holding one copied pre-logout Admin token",
            asset="The binding between Admin identity, privilege and an active session",
            precondition="Token capture occurred before logout; the lab tests replay, not the theft method.",
            weakness="Logout clears client state but leaves the server session active",
            mechanism="The vulnerable logout deletes only the cookie and never changes the authoritative session row.",
            failed_decision="Possession of an old bearer token is accepted as proof of a still-active session.",
            attack_technique="Replay the copied token after the user believes the session has ended.",
            trust_boundary="A bearer token crosses from an untrusted client into the privileged route; the token identifies a session, but current authority must come from server-side lifecycle state.",
            security_property="Authentication lifecycle, privilege control and session revocation",
            likelihood="Once copied, the bearer token can be replayed until expiry unless the server actively revokes it.",
            threat_chain="Copy a valid Admin token -> Admin logs out only in the browser -> server row remains active -> replay still reaches privileged data.",
            impact="The demonstrated token has Admin privilege, so continued use can preserve sensitive authority during logout or incident response.",
            if_unfixed="Logout, shared-device cleanup and attempted incident containment cannot terminate a stolen session during its remaining lifetime.",
            vulnerable_heading="The browser logs out but the token stays active",
            secure_heading="The server revokes the session lifecycle",
            control="Mark the session inactive and check existence, active state, expiry and role on every protected request.",
            why_it_works="A copied token cannot override the server's revoked state, while a newly issued active token can still be used.",
            comparison="Vulnerable treats bearer possession as continuing authority; secure treats the token as an identifier and re-evaluates active state, expiry and role server-side.",
            observed_change="Old-token replay changes from 200 with Admin data to 401 with the session row inactive.",
            legitimate_check="A fresh Admin token returns 200, while a customer token receives 403.",
            before="I assumed removing a browser cookie meant the user was logged out.",
            after="I now model a session as a lifecycle object and keep the server authoritative about revocation, expiry and privilege.",
            mistake="The reasoning error was equating client cleanup with invalidation; deleting one browser cookie cannot change a copy already held elsewhere.",
            correction="The guided comparison changes authoritative state before replay: the old token becomes 401 and inactive, while a separately issued fresh Admin token still works.",
            redo="If I extended this module, I would specify rotation, fixation defence, multi-device revocation and session-store outage behaviour rather than treating logout as the whole lifecycle.",
            course_topic="Authentication lifecycle and verifying every privileged request",
            course_source="Week 7 Engineering, slide 38; Week 4 Engineering, slides 53-55",
            supports="The experiment supports a post-logout replay claim for one synthetic server-side session design.",
            does_not_prove="It does not demonstrate token theft or solve TLS, fixation, rotation, CSRF, cookie policy or session-store compromise.",
            residual_risks=["token theft before logout", "fixation and rotation", "session-store security and availability"],
        ),
        "deep_dive": {
            "attack_chain": [
                "Admin signs in and receives a synthetic bearer token backed by a server session row.",
                "A second party is assumed to have copied that token before logout.",
                "The vulnerable logout deletes only the browser cookie and leaves the session row active.",
                "Replaying the copied token still satisfies the privileged check until the token expires.",
            ],
            "insufficient_fix": "Deleting the local cookie changes one browser's UI state, not the authority carried by a copied bearer token. A shorter expiry reduces the window but cannot provide immediate revocation.",
            "control_choice": "I made session activity authoritative on the server and check existence, active state, expiry and role on every privileged request. Logout changes that state before the old token is tested again.",
            "evidence_reading": "The guided flow keeps the business sequence constant: login, logout, replay, fresh login. Old-token replay changes from 200 to 401 and the old session changes from active to inactive, while a fresh Admin session remains 200.",
            "tradeoff": "Authoritative revocation makes the session store part of the security decision and an availability dependency. The lab does not prevent token capture, and a production design still needs rotation, fixation defence and multi-device policy.",
        },
        "contract": _contract(
            ("A fresh Admin token reaches the dashboard.", "status 200 and Admin marker present"),
            ("The old token still works after vulnerable logout.", "replay status 200 and session active=true"),
            ("Secure logout permanently revokes the old token.", "replay status 401 and session active=false"),
            ("A new secure login creates a different working token.", "new token differs and status 200"),
        ),
    },
    {
        "id": "a08",
        "owasp": "A08:2025",
        "name": "Software or Data Integrity Failures",
        "depth": "Compact",
        "scenario": "Well-formed but modified JSON changes a product price.",
        "control": "Verify an HMAC over the exact request bytes before mutation.",
        "analysis": _analysis(
            actor="A caller or intermediary able to submit or change an update body",
            asset="Synthetic product price integrity",
            precondition="The integration endpoint is reachable and the body can be altered or replaced.",
            weakness="Mutable client data has no authenticity or integrity binding",
            mechanism="The vulnerable route parses valid JSON and updates state without checking who authenticated the bytes.",
            failed_decision="Well-formed input is treated as proof that the message is trusted and unchanged.",
            attack_technique="Modify the intended price while replaying a signature for different bytes or omitting it.",
            trust_boundary="Raw update bytes cross from an integration caller into authoritative price state; the shared key and verification decision remain server-side.",
            security_property="Integrity and origin authentication of a state-changing message",
            likelihood="Any reachable caller can try a modified body when the endpoint has no valid message authenticator.",
            threat_chain="Change the intended JSON bytes -> parser still accepts the schema -> unsigned update reaches the database -> authoritative price is corrupted.",
            impact="A valid-looking request can corrupt authoritative prices and downstream business data.",
            if_unfixed="Schema-valid but unauthenticated messages can silently change protected state.",
            vulnerable_heading="Valid JSON is mistaken for trusted JSON",
            secure_heading="Exact bytes require a valid authenticator",
            control="Verify an HMAC over the exact raw body before parsing or changing the database.",
            why_it_works="Any byte change produces a different authenticator unless the caller holds the shared key.",
            comparison="Vulnerable parses and trusts a well-formed body before any authenticity decision; secure authenticates the exact bytes before parsing or mutation.",
            observed_change="The tampered update changes from accepted to 401 with price state unchanged.",
            legitimate_check="An exact body with a valid HMAC returns API status 204 and updates the intended price.",
            before="I treated input validation and message integrity as roughly the same check.",
            after="I now separate well-formedness, integrity/authentication and freshness; HMAC addresses the middle property, not all three.",
            mistake="The reasoning error was treating schema validity as a trust signal; an attacker can create perfectly valid JSON containing an unauthorised price.",
            correction="The secure path verifies the exact raw bytes first, so a stale signature cannot authorise the changed body and the database remains unchanged.",
            redo="If I extended this module, I would add nonce or timestamp replay rules, key rotation and a canonicalisation protocol instead of claiming HMAC alone provides freshness.",
            course_topic="Message integrity, HMAC and the difference from plain hashing",
            course_source="Week 5 Engineering, slides 40-46; Week 7 Engineering, slides 8-10",
            supports="The experiment supports an exact-body HMAC claim for one local price-update message.",
            does_not_prove="It does not provide freshness, replay prevention, key rotation, sender separation or secure key storage.",
            residual_risks=["message replay", "shared-key storage and rotation", "canonicalisation across systems"],
        ),
        "contract": _contract(
            ("An intended update is accepted.", "API status 204 and intended price stored"),
            ("A changed body is accepted with a stale signature.", "API status 204 and tampered price stored"),
            ("The identical changed body is rejected.", "status 401, integrity_valid=false and price unchanged"),
            ("An exact signed body is accepted.", "API status 204 and intended price stored"),
        ),
    },
    {
        "id": "a09",
        "owasp": "A09:2025",
        "name": "Security Logging and Alerting Failures",
        "depth": "Compact",
        "scenario": "Three rejected Admin logins create no security signal.",
        "control": "Record minimised events and apply a time-window alert rule.",
        "analysis": _analysis(
            actor="A source repeatedly guessing the synthetic Admin password",
            asset="Detection capability and incident-response evidence",
            precondition="The login endpoint is reachable and repeated attempts can be made.",
            weakness="Security-relevant authentication failures are neither recorded nor correlated",
            mechanism="The vulnerable path returns 401 but leaves event and alert counts at zero.",
            failed_decision="Rejecting each request is assumed to be enough even when the attack sequence remains invisible.",
            attack_technique="Repeat online guesses and rely on the absence of useful telemetry or alerting.",
            trust_boundary="Authentication outcomes cross into the audit and alert pipeline; only minimised security fields should cross, while passwords and tokens must not.",
            security_property="Detection, accountability and the ability to respond",
            likelihood="Repeated login attempts are easy to automate; the lab limits its claim to one subject and source.",
            threat_chain="Repeat guesses -> each request is rejected in isolation -> no events are correlated -> defenders receive no actionable signal while attempts continue.",
            impact="Without measurable events, defenders cannot recognise, investigate or respond to the sequence.",
            if_unfixed="An attack can continue unnoticed and leave too little evidence for reliable incident analysis.",
            vulnerable_heading="Each failure disappears after the response",
            secure_heading="Events become a measurable sequence",
            control="Record minimised structured events and alert once after three failures within 60 seconds.",
            why_it_works="The time window and threshold turn separate requests into one observable security condition without storing passwords or tokens.",
            comparison="Vulnerable stops at a 401 response; secure also emits a privacy-minimised event and evaluates the event sequence against an explicit window and threshold.",
            observed_change="Three 401 responses change from zero events/alerts to three events and one alert.",
            legitimate_check="A valid login records AUTH_SUCCESS without producing a failure alert.",
            before="I assumed that producing logs meant an application had detection.",
            after="I now distinguish logging from detection and define the event, window and threshold together with privacy and alert-fatigue trade-offs.",
            mistake="The reasoning error was treating individual log lines or 401 responses as detection; neither defines when a sequence becomes actionable.",
            correction="The secure experiment fixes the event schema, clock window and threshold, then verifies the 0, 0, 1 alert sequence without recording the submitted password.",
            redo="If I extended this module, I would test distributed and low-and-slow sources, alert quality and tamper-resistant storage before proposing a production response rule.",
            course_topic="Measurement, digital traces and false-positive/false-negative trade-offs",
            course_source="Week 3 Core, slide 5; Week 4 Engineering, slides 47-48; Week 2 Engineering, slides 10-12",
            supports="The experiment supports one deterministic three-failure/60-second detection rule.",
            does_not_prove="It does not cover distributed sources, low-and-slow attacks, log tampering, retention, response playbooks or alert quality in production.",
            residual_risks=["low-and-slow attacks", "alert fatigue and false positives", "log integrity and response process"],
        ),
        "contract": _contract(
            ("Valid vulnerable login succeeds.", "status 200 and authenticated=true"),
            ("Three failures leave no signal.", "all status 401; event count=0 and alert count=0"),
            ("The third secure failure creates one alert.", "event counts 1,2,3 and alert counts 0,0,1"),
            ("Valid secure login records success without a failure alert.", "AUTH_SUCCESS exists and alert count remains zero"),
        ),
    },
    {
        "id": "a10",
        "owasp": "A10:2025",
        "name": "Mishandling of Exceptional Conditions",
        "depth": "Compact",
        "scenario": "A failed authorization dependency is treated as permission.",
        "control": "Represent uncertainty explicitly and fail closed.",
        "analysis": _analysis(
            actor="Alice requesting an Admin-only export during a policy-service failure",
            asset="Confidentiality of the synthetic customer export",
            precondition="The authorization dependency fails while a protected request is being decided.",
            weakness="An exceptional authorization condition is handled as allow",
            mechanism="A broad exception handler substitutes True when the policy decision is unavailable.",
            failed_decision="Could not determine permission is treated as permission granted.",
            attack_technique="Trigger or wait for a dependency failure while requesting protected data.",
            trust_boundary="A policy dependency's allow, deny or unavailable result crosses into the protected export decision; uncertainty must not become authority.",
            security_property="Confidentiality and correct authorization under failure",
            likelihood="The lab deliberately supplies the dependency failure; real likelihood depends on reliability and attacker influence.",
            threat_chain="Policy dependency fails -> broad handler substitutes allow -> protected branch executes -> Alice receives the Admin-only export.",
            impact="An availability incident becomes an authorization bypass that releases protected data.",
            if_unfixed="Every relevant dependency outage can silently weaken the access-control policy at the moment it is least observable.",
            vulnerable_heading="Unknown permission becomes allow",
            secure_heading="Unknown permission becomes unavailable",
            control="Keep deny, allow and dependency failure distinct; return 503 without the export when no decision is available.",
            why_it_works="Protected data is released only after an explicit healthy allow, never because an exception occurred.",
            comparison="Vulnerable collapses unavailable into True; secure preserves three states and releases data only for an explicit healthy allow.",
            observed_change="The same failure changes from 200 with the export marker to 503 without it.",
            legitimate_check="A healthy Admin request returns 200 and a healthy Alice request returns 403.",
            before="I thought exception handling mainly protected application availability.",
            after="I now treat exceptional paths as part of the security policy and make the confidentiality-versus-availability trade-off explicit.",
            mistake="The reasoning error was optimising continuity without preserving the authorization invariant; returning something during failure is not safe if that thing is protected data.",
            correction="The secure branch represents dependency failure separately and returns 503 with no export, while healthy Admin allow and healthy Alice deny still behave correctly.",
            redo="If I extended this module, I would add bounded timeouts, circuit breaking, monitoring and a recovery runbook while retaining the same fail-closed release rule.",
            course_topic="Fail-safe defaults, safe failure and risk trade-offs",
            course_source="Week 2 Engineering, slides 34-35; Week 2 Core, slides 30-39",
            supports="The experiment supports a fail-open versus fail-closed claim for one synthetic authorization dependency.",
            does_not_prove="It does not solve timeouts, retries, circuit breaking, monitoring, recovery or every dependency failure mode.",
            residual_risks=["dependency reliability", "retry and timeout policy", "monitoring and recovery"],
        ),
        "contract": _contract(
            ("A healthy explicit Admin allow returns the export.", "status 200 and export marker present"),
            ("Alice receives the export when policy evaluation errors.", "status 200, fail_open=true and export_returned=true"),
            ("The same error fails closed.", "status 503 and export_returned=false"),
            ("Healthy Admin succeeds and healthy Alice is denied.", "Admin 200; Alice 403"),
        ),
    },
]


for index, lab in enumerate(LABS):
    lab["previous_id"] = LABS[index - 1]["id"] if index else None
    lab["next_id"] = LABS[index + 1]["id"] if index + 1 < len(LABS) else None


LAB_BY_ID = {lab["id"]: lab for lab in LABS}
